#ifndef FBX2FSEQ_SRC_CORE_COMPONENTS_LOADER_FBX_MESH_LOADER_HPP_
#define FBX2FSEQ_SRC_CORE_COMPONENTS_LOADER_FBX_MESH_LOADER_HPP_

#include"fbxsdk.h"

class FbxMeshLoader : public FbxMesh {

};

#endif // FBX2FSEQ_SRC_CORE_COMPONENTS_LOADER_FBX_MESH_LOADER_HPP_